<?php

namespace App\Services\DevApps;

use App\Models\DevApp;
use Illuminate\Support\Facades\File;
use RuntimeException;

/**
 * Generates the Traefik dynamic configuration that mounts a {@see DevApp}
 * under a path on datakita's own domain.
 *
 * Why generate this instead of letting Dokploy's Domain tab create the
 * router: the middleware chain below is not optional. Mounting somebody
 * else's application on datakita's origin is only tolerable if every request
 * to it goes through the ForwardAuth check first and arrives at the app with
 * datakita's session cookie removed. A generated file can't have a step
 * forgotten; a checkbox in a UI can.
 *
 * The chain, in order — the order is the whole point:
 *
 *   1. <slug>-auth      ForwardAuth back to datakita. Still sees the Cookie
 *                       header, which is how it identifies the user. Returns
 *                       the identity headers on success, 302 to /login or
 *                       403 otherwise.
 *   2. devapp-scrub     Deletes the Cookie header. Everything after this
 *                       point — including the app's own container — never
 *                       sees a datakita session token.
 *   3. <slug>-strip     Optional StripPrefix so an app written for the domain
 *                       root works unmodified.
 *
 * Read the "Residual risk" section of docs/DEVELOP_PORTAL.md before treating
 * this as a sandbox. It is not one: it protects the session token from the
 * app's *server*, not datakita's origin from the app's *browser-side JS*.
 */
class TraefikConfigBuilder
{
    /**
     * Name of the shared middleware that deletes the Cookie header. Defined
     * once per file; identical definitions across files are harmless.
     */
    private const SCRUB_MIDDLEWARE = 'devapp-scrub-cookie';

    /**
     * Render the complete dynamic-config document for one app.
     */
    public function build(DevApp $app): string
    {
        $host        = $this->host();
        $slug        = $app->slug;
        $router      = "devapp-{$slug}";
        $mountPath   = $app->mountPath();
        $service     = $this->serviceUrl($app);
        $entryPoints = $this->yamlList(array_map('trim', config('devapps.traefik.entrypoints', ['websecure'])));
        $priority    = (int) config('devapps.traefik.priority', 100);
        $resolver    = (string) config('devapps.traefik.cert_resolver', 'letsencrypt');
        $authUrl     = rtrim((string) config('devapps.forward_auth_base'), '/') . "/develop/authz/{$slug}";

        $headers = array_values(config('devapps.identity_headers', []));

        $middlewares = ["{$router}-auth", self::SCRUB_MIDDLEWARE];
        if ($app->strip_prefix) {
            $middlewares[] = "{$router}-strip";
        }

        $lines = [];
        $lines[] = "# Generated by datakita — do not edit by hand.";
        $lines[] = "# App: {$app->name} (slug: {$slug}, owner: {$app->owner_user_id})";
        $lines[] = "# Regenerate from /develop/{$slug}.";
        $lines[] = '';
        $lines[] = 'http:';
        $lines[] = '  routers:';
        $lines[] = "    {$router}:";
        $lines[] = "      rule: \"Host(`{$host}`) && PathPrefix(`{$mountPath}`)\"";
        $lines[] = "      priority: {$priority}";
        $lines[] = "      entryPoints: {$entryPoints}";
        $lines[] = "      service: {$router}";
        $lines[] = '      middlewares:';
        foreach ($middlewares as $mw) {
            $lines[] = "        - {$mw}@file";
        }
        $lines[] = '      tls:';
        $lines[] = "        certResolver: {$resolver}";
        $lines[] = '';
        $lines[] = '  middlewares:';

        // 1 — the access decision.
        $lines[] = "    {$router}-auth:";
        $lines[] = '      forwardAuth:';
        $lines[] = "        address: \"{$authUrl}\"";
        $lines[] = '        trustForwardHeader: true';
        $lines[] = '        authResponseHeaders:';
        foreach ($headers as $header) {
            $lines[] = "          - {$header}";
        }
        $lines[] = '';

        // 2 — the session token never leaves datakita.
        $lines[] = '    ' . self::SCRUB_MIDDLEWARE . ':';
        $lines[] = '      headers:';
        $lines[] = '        customRequestHeaders:';
        $lines[] = '          # Empty value deletes the header. Must stay after the';
        $lines[] = '          # forwardAuth middleware, which needs it to read the session.';
        $lines[] = '          Cookie: ""';
        $lines[] = '';

        // 3 — optional path rewrite.
        if ($app->strip_prefix) {
            $lines[] = "    {$router}-strip:";
            $lines[] = '      stripPrefix:';
            $lines[] = '        prefixes:';
            $lines[] = "          - \"{$mountPath}\"";
            $lines[] = '';
        }

        $lines[] = '  services:';
        $lines[] = "    {$router}:";
        $lines[] = '      loadBalancer:';
        $lines[] = '        servers:';
        $lines[] = "          - url: \"{$service}\"";
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * File name this app's config is written as.
     */
    public function fileName(DevApp $app): string
    {
        return "devapp-{$app->slug}.yml";
    }

    /**
     * Whether the portal can write config itself, or can only render it for
     * an admin to paste.
     */
    public function canWrite(): bool
    {
        $path = config('devapps.traefik.dynamic_path');

        return is_string($path) && $path !== '' && is_dir($path) && is_writable($path);
    }

    /**
     * Write (or rewrite) the app's config file.
     *
     * @return string the path written
     */
    public function write(DevApp $app): string
    {
        if (! $this->canWrite()) {
            throw new RuntimeException(
                'DEVAPPS_TRAEFIK_DYNAMIC_PATH is not set or not writable, so the routing config cannot be applied automatically.'
            );
        }

        $path = rtrim((string) config('devapps.traefik.dynamic_path'), '/\\')
            . DIRECTORY_SEPARATOR . $this->fileName($app);

        File::put($path, $this->build($app));

        return $path;
    }

    /**
     * Remove the app's config file, taking its route offline. Safe to call
     * when the file was never written.
     */
    public function remove(DevApp $app): void
    {
        $dir = config('devapps.traefik.dynamic_path');

        if (! is_string($dir) || $dir === '') {
            return;
        }

        $path = rtrim($dir, '/\\') . DIRECTORY_SEPARATOR . $this->fileName($app);

        if (File::exists($path)) {
            File::delete($path);
        }
    }

    /**
     * Render a flow-style YAML sequence, e.g. ["websecure", "web"].
     *
     * @param  array<int, string>  $items
     */
    private function yamlList(array $items): string
    {
        $quoted = array_map(fn ($item) => '"' . addslashes($item) . '"', array_values(array_filter($items)));

        return '[' . implode(', ', $quoted) . ']';
    }

    /**
     * Hostname datakita and every dev app share.
     */
    private function host(): string
    {
        $url = (string) (config('devapps.public_host_url') ?: config('app.url'));

        return parse_url($url, PHP_URL_HOST) ?: 'localhost';
    }

    /**
     * Internal address of the app's container.
     *
     * Dokploy names the Swarm service after the application's appName, so it
     * resolves on the shared overlay network without publishing a port.
     */
    private function serviceUrl(DevApp $app): string
    {
        $name = $app->dokploy_app_name ?: $app->slug;

        return "http://{$name}:{$app->container_port}";
    }
}
